name: arabamda_ne_var
description: "Araç arıza teşhis ve bakım takip uygulaması."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.20.2               # Tarih/para formatı için
  geolocator: ^12.0.0
  geocoding: ^4.0.0
  url_launcher: ^6.2.1
  permission_handler: ^12.0.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_database: ^11.3.9
  firebase_dynamic_links: ^6.1.9
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  timezone: ^0.10.1
  share_plus: ^10.0.0
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  generate: true

# L10n ayarları (kök seviyede)
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_tr.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations